name: test_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  google_ml_kit: ^0.19.0
  google_mlkit_commons: ^0.9.0  # Updated from ^0.5.0
  image_picker: ^1.0.1
  camera: ^0.10.5+2
  path: ^1.8.3
  path_provider: ^2.0.15
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true